name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: briz-felipe
          outputs: |
            ./docs/snake.svg

      - name: Commit e Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Felipe Briz
          message: "update contribution snake"
          add: "dist/snake.svg"
