name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: briz-felipe
          outputs: |
            ./docs/snake.svg

      - name: Commit e Push snake.svg
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Felipe Briz
          message: "update snake contribution graph"
          add: "docs/snake.svg"
